# -*- coding: utf-8 -*-
"""fine tune small bert

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18FmmghYb598GH7eWhopxq98f5v4WUkAV
"""

import csv
def readTsv(filname):
    bytes = open(filname, 'r', encoding='utf8')
    read_ = csv.reader(bytes, delimiter='\t')
    keys = next(read_)
    ret = dict();
    for i in range(len(keys)):
        ret[keys[i]] = []
    for row in read_:
        for i in range(len(keys)):
            ret[keys[i]].append(row[i])
    return ret
tsv = readTsv('assets/train.tsv')
print(tsv['path'][0])
print(tsv['path'][1])